# Generated by Django 3.2.6 on 2021-09-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='01-01-2021', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='state_province',
            field=models.CharField(default='N/A', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='website',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('publication_date', models.DateField()),
                ('authors', models.ManyToManyField(to='front.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.publisher')),
            ],
        ),
    ]
